version: '3'

services:
  backend:
    build: ./backend
    restart: always
    volumes:
      - static_volume:/backend/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.prod
    depends_on:
      - db
    entrypoint: ./scripts/backend-prod-entrypoint.sh

  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.prod

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
      - nginx
    entrypoint: ./scripts/frontend-prod-entrypoint.sh

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/backend/staticfiles
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume: